generated-files-y += linux-user/i386/syscall_nr.h

syshdr := $(SRC_PATH)/linux-user/i386/syscallhdr.sh
%/syscall_nr.h: $(SRC_PATH)/linux-user/i386/syscall_32.tbl $(syshdr)
	$(call quiet-command, sh $(syshdr) $< $@ $(TARGET_SYSTBL_ABI),"GEN","$@")
