#ifndef MICROBLAZE_TARGET_SYSCALL_H
#define MICROBLAZE_TARGET_SYSCALL_H

#define UNAME_MACHINE "microblaze"
#define UNAME_MINIMUM_RELEASE "2.6.32"

#define TARGET_CLONE_BACKWARDS
#define TARGET_MCL_CURRENT 1
#define TARGET_MCL_FUTURE  2
#define TARGET_MCL_ONFAULT 4

#define TARGET_WANT_NI_OLD_SELECT

#endif
