#!/usr/bin/env bash
#
# Test case for qemu-img convert to NBD
#
# Copyright (C) 2015 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# creator
owner=mreitz@redhat.com

seq="$(basename $0)"
echo "QA output created by $seq"

status=1	# failure is the default!

_cleanup()
{
    _cleanup_test_img
    rm -f "$SRC_IMG"
}
trap "_cleanup; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_supported_fmt raw
_supported_proto nbd
_supported_os Linux

SRC_IMG="$TEST_DIR/source.$IMGFMT"

_make_test_img 1M
$QEMU_IMG create -f $IMGFMT "$SRC_IMG" 1M | _filter_img_create

$QEMU_IO -c 'write -P 42 0 1M' "$SRC_IMG" | _filter_qemu_io

$QEMU_IMG convert -n -f $IMGFMT -O raw "$SRC_IMG" "$TEST_IMG"

$QEMU_IO -c 'read -P 42 0 1M' "$TEST_IMG" | _filter_qemu_io


# success, all done
echo
echo '*** done'
rm -f $seq.full
status=0
