#!/usr/bin/env bash
# group: rw quick
#
# Test generic image creation fallback (by using NBD)
#
# Copyright (C) 2019 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# creator
owner=hreitz@redhat.com

seq=$(basename $0)
echo "QA output created by $seq"

status=1	# failure is the default!

_cleanup()
{
    _cleanup_test_img
}
trap "_cleanup; exit \$status" 0 1 2 3 15

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_supported_fmt raw
_supported_proto nbd
_supported_os Linux


_make_test_img 64M

echo
echo '--- Testing creation ---'

$QEMU_IMG create -f qcow2 "$TEST_IMG" 64M | _filter_img_create
$QEMU_IMG info "$TEST_IMG" | _filter_img_info

echo
echo '--- Testing creation for which the node would need to grow ---'

# NBD does not support resizing, so this will fail
$QEMU_IMG create -f qcow2 -o preallocation=metadata "$TEST_IMG" 64M 2>&1 \
    | _filter_img_create

# success, all done
echo "*** done"
rm -f $seq.full
status=0
