obj-y = lance.o tcx.o sun4m_iommu.o slavio_intctl.o
obj-y += slavio_timer.o slavio_misc.o sparc32_dma.o
obj-y += cs4231.o eccmemctl.o sbi.o sun4c_intctl.o

# GRLIB
obj-y += grlib_gptimer.o grlib_irqmp.o grlib_apbuart.o

obj-y := $(addprefix ../,$(obj-y))

obj-y += sun4m.o leon3.o
