#!/bin/bash -e
#
# Build and run the TCG tests
#
# Copyright (c) 2021 Linaro Ltd.
#
# Authors:
#  Alex Bennée <alex.bennee@linaro.org>
#
# This work is licensed under the terms of the GNU GPL, version 2
# or (at your option) any later version. See the COPYING file in
# the top-level directory.

. common.rc

cd "$BUILD_DIR"

# although we are not building QEMU itself we still need a configured
# build for the unit tests to be built and run
TARGET_LIST=${TARGET_LIST:-$DEF_TARGET_LIST} \
build_qemu
check_qemu check-tcg
