S390X_SRC=$(SRC_PATH)/tests/tcg/s390x
VPATH+=$(S390X_SRC)
QEMU_OPTS=-action panic=exit-failure -kernel

%: %.S
	$(CC) -march=z13 -m64 -nostartfiles -static -Wl,-Ttext=0 \
		-Wl,--build-id=none $< -o $@

TESTS += unaligned-lowcore
