# Makefile.include for AArch64 targets
#
# We don't have any bigendian build tools so we only use this for AArch64

ifeq ($(TARGET_NAME),aarch64)
DOCKER_IMAGE=debian-buster-arm64-cross
DOCKER_CROSS_COMPILER=aarch64-linux-gnu-gcc
endif
