.\" $Header: /home/paul/qemu/svnmerge/qemu-cvs/qemu/qemu-mkcow.1,v 1.1 2004-03-26 22:42:54 bellard Exp $
.\"
.\"	transcript compatibility for postscript use.
.\"
.\"	synopsis:  .P! <file.ps>
.\"
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
'\" t 
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n  
.TH "QEMU" "8" 
.SH "NAME" 
qemu-mkcow \(em create a copy-on-write file for qemu 
.SH "SYNOPSIS" 
.PP 
\fBqemu-mkcow\fR [\fB-h\fP]  [\fB-f \fImaster_disk_image\fR\fP]  [\fIcow_image\fR]  [\fB\fIcow_size\fR\fP]  
.SH "DESCRIPTION" 
.PP 
The \fBqemu-mkcow\fR command creates a 
persistent copy-on-write file for \fBqemu\fR. 
 
.PP 
\fBqemu\fR can be used in a "copy-on-write" mode, 
where changes made by \fBqemu\fR do not actually 
change the disk image file.  One way is to invoke 
\fBqemu\fR with -snapshot: these changes 
are stored in a temporary file, which is discarded when  
\fBqemu\fR exits. 
 
.PP 
\fBqemu-mkcow\fR creates an explicit copy-on-write 
file where changes are to be stored: this way, changes made 
inside \fBqemu\fR will still be there next time you 
run it, although the master disk image isn't ever changed. 
 
.PP 
The usual method is to create the master image, then create a 
copy-on-write file using \fBqemu-mkcow\fR with 
\fB-f\fP.  The filename of the master image is stored 
inside the generated copy-on-write file: it must not be modified 
after this is run! 
 
.PP 
If no master file is specified, the effect is that of a 
blank master of size \fIcow_size\fR. 
 
.SH "SEE ALSO" 
.PP 
qemu(1), qemu-fast(1). 
.SH "AUTHOR" 
.PP 
This manual page was written by Paul Russell prussell@debian.org for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
.\" created by instant / docbook-to-man, Fri 12 Mar 2004, 05:58 
