#Default configuration for cskyv2eb-softmmu

CONFIG_CSKY_MAC=y
CONFIG_CSKY_MAC2=y
CONFIG_SERIAL=y
CONFIG_PTIMER=y
CONFIG_PCKBD=y
CONFIG_NAND=y
CONFIG_FRAMEBUFFER=y
CONFIG_SD=y
CONFIG_CSKY_IIS=y
CONFIG_CSKY_NFC=y
CONFIG_CSKY_UART=y
CONFIG_CSKY_LCDC=y
CONFIG_CSKY_DMA=y
CONFIG_CSKY_INTC=y
CONFIG_CSKY_TCIP=y
CONFIG_CSKY_EXIT=y
CONFIG_CSKY_MEMLOG=y
CONFIG_CSKY_SDHC=y
CONFIG_CSKY_TIMER=y
CONFIG_SMARTL=y
CONFIG_SMARTH=y
