# Default configuration for sh4eb-softmmu

CONFIG_PCI=y
CONFIG_PCI_DEVICES=y
CONFIG_SERIAL=y
CONFIG_PFLASH_CFI02=y
CONFIG_SH4=y
CONFIG_IDE_MMIO=y
CONFIG_SM501=y
CONFIG_TEST_DEVICES=y
CONFIG_I82378=y
CONFIG_I82374=y
CONFIG_R2D=y
CONFIG_SHIX=y
