# Default configuration for sparc64-softmmu

CONFIG_PCI=y
CONFIG_PCI_DEVICES=y
CONFIG_M48T59=y
CONFIG_SERIAL=y
CONFIG_SERIAL_ISA=y
CONFIG_PARALLEL=y
CONFIG_PCKBD=y
CONFIG_FDC=y
CONFIG_IDE_CMD646=y
CONFIG_PCI_SABRE=y
CONFIG_SIMBA=y
CONFIG_SUNHME=y
CONFIG_MC146818RTC=y
CONFIG_TEST_DEVICES=y
CONFIG_SUN4V_RTC=y
CONFIG_SUN4U=y
CONFIG_NIAGARA=y
