# Default configuration for xbox-softmmu

include pci.mak
include usb.mak
CONFIG_VGA=y
CONFIG_VGA_PCI=y
CONFIG_VMMOUSE=y
CONFIG_I8254=y
CONFIG_PCSPK=y
CONFIG_PCKBD=y
CONFIG_FDC=y
CONFIG_ACPI=y
CONFIG_APM=y
CONFIG_DMA=y
CONFIG_IDE_ISA=y
CONFIG_IDE_PIIX=y
CONFIG_SOUND=y
CONFIG_HPET=y
CONFIG_I8259=y
CONFIG_PFLASH_CFI01=y
CONFIG_XBOX=y
