generated-files-y += linux-user/sparc/syscall_nr.h

syshdr := $(SRC_PATH)/linux-user/sparc/syscallhdr.sh
%/syscall_nr.h: $(SRC_PATH)/linux-user/sparc/syscall.tbl $(syshdr)
	$(call quiet-command, sh $(syshdr) $< $@ $(TARGET_SYSTBL_ABI),"GEN","$@")
