obj-$(call lnot,$(CONFIG_HAX))  += hax-stub.o
obj-$(call lnot,$(CONFIG_HVF))  += hvf-stub.o
obj-$(call lnot,$(CONFIG_WHPX)) += whpx-stub.o
obj-$(call lnot,$(CONFIG_KVM))  += kvm-stub.o
obj-$(call lnot,$(CONFIG_TCG))  += tcg-stub.o
obj-$(call lnot,$(CONFIG_XEN))  += xen-stub.o
