/* List of comma-separated changed AML files to ignore */
"tests/data/acpi/virt/DSDT",
"tests/data/acpi/virt/APIC.memhp",
"tests/data/acpi/virt/APIC.numamem",
"tests/data/acpi/virt/DSDT.memhp",
"tests/data/acpi/virt/DSDT.numamem",
"tests/data/acpi/virt/FACP.memhp",
"tests/data/acpi/virt/FACP.numamem",
"tests/data/acpi/virt/GTDT.memhp",
"tests/data/acpi/virt/GTDT.numamem",
"tests/data/acpi/virt/MCFG.memhp",
"tests/data/acpi/virt/MCFG.numamem",
"tests/data/acpi/virt/SLIT.memhp",
"tests/data/acpi/virt/SPCR.memhp",
"tests/data/acpi/virt/SPCR.numamem",
"tests/data/acpi/virt/SRAT.memhp",
"tests/data/acpi/virt/SRAT.numamem",
