include ../rh-virtio.mak

CONFIG_PCI=y
CONFIG_S390_CCW_VIRTIO=y
CONFIG_S390_FLIC=y
CONFIG_S390_FLIC_KVM=y
CONFIG_SCLPCONSOLE=y
CONFIG_SCSI=y
CONFIG_VFIO=y
CONFIG_VFIO_AP=y
CONFIG_VFIO_CCW=y
CONFIG_VFIO_PCI=y
CONFIG_VHOST_USER=y
CONFIG_VIRTIO_CCW=y
CONFIG_WDT_DIAG288=y
CONFIG_VHOST_VSOCK=y
CONFIG_VHOST_USER_VSOCK=y
CONFIG_VHOST_USER_FS=y
CONFIG_IOMMUFD=y
