#!/usr/bin/env python3

import sys

print('''This unmaintained and undocumented script was removed in preference
for qmp-shell. The assumption is that most users are using either
qmp-shell, socat, or pasting/piping JSON into stdio. The duplication of
facilities here is unwanted, and the divergence of syntax harmful.''',
      file=sys.stderr)

sys.exit(1)
