#!/usr/bin/env python3

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..', 'python'))
from qemu.qmp.qom_fuse import QOMFuse


if __name__ == '__main__':
    sys.exit(QOMFuse.entry_point())
