#!/usr/bin/env python3

import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..', 'python'))
from qemu.utils.qom import QOMTree


if __name__ == '__main__':
    sys.exit(QOMTree.entry_point())
