common-obj-y += virtio-rng.o
common-obj-$(CONFIG_VIRTIO_PCI) += virtio-pci.o
common-obj-y += virtio-bus.o
common-obj-y += virtio-mmio.o
common-obj-$(CONFIG_VIRTIO_BLK_DATA_PLANE) += dataplane/

obj-y += virtio.o virtio-balloon.o 
obj-$(CONFIG_LINUX) += vhost.o vhost-backend.o
