include $(BUILD_DIR)/tests/tcg/s390x-linux-user/config-target.mak

SUBDIR = $(SRC_PATH)/linux-user/s390x
VPATH += $(SUBDIR)

all: $(SUBDIR)/vdso.so

$(SUBDIR)/vdso.so: vdso.S vdso.ld vdso-asmoffset.h
	$(CC) -o $@ -nostdlib -shared -Wl,-h,linux-vdso64.so.1 \
	  -Wl,--build-id=sha1 -Wl,--hash-style=both \
	  -Wl,-T,$(SUBDIR)/vdso.ld $<
