#ifndef S390X_TARGET_SYSCALL_H
#define S390X_TARGET_SYSCALL_H

#define UNAME_MACHINE "s390x"
#define UNAME_MINIMUM_RELEASE "2.6.32"

#define TARGET_CLONE_BACKWARDS2
#define TARGET_MCL_CURRENT 1
#define TARGET_MCL_FUTURE  2
#define TARGET_MCL_ONFAULT 4

#endif /* S390X_TARGET_SYSCALL_H */
