ifeq ($(CONFIG_SOFTMMU), y)
devices-dirs-$(call lor,$(CONFIG_VIRTIO_9P),$(call land,$(CONFIG_VIRTFS),$(CONFIG_XEN))) += 9pfs/
devices-dirs-y += acpi/
devices-dirs-y += adc/
devices-dirs-y += audio/
devices-dirs-y += block/
devices-dirs-y += char/
devices-dirs-y += cpu/
devices-dirs-y += display/
devices-dirs-y += dma/
devices-dirs-y += gpio/
devices-dirs-$(CONFIG_HYPERV) += hyperv/
endif

common-obj-y += $(devices-dirs-y)
common-obj-m += display/
common-obj-m += usb/
obj-y += $(devices-dirs-y)
