
LCITOOL_REFRESH = $(SRC_PATH)/tests/lcitool/refresh

lcitool:
	@echo 'Manage build environment manifests'
	@echo
	@echo 'Available targets:'
	@echo
	@echo '    lcitool:             Print this help.'
	@echo '    lcitool-refresh:     Re-generate all build environment manifests.'
	@echo

lcitool-help: lcitool

lcitool-refresh:
	$(call quiet-command, cd $(SRC_PATH) && git submodule update --init tests/lcitool/libvirt-ci)
	$(call quiet-command, $(PYTHON) $(LCITOOL_REFRESH))
