# -*- Mode: makefile -*-
#
# A super basic AArch64 BE makefile. As we don't have any big-endian
# libc available the best we can do is a basic Hello World.

AARCH64BE_SRC=$(SRC_PATH)/tests/tcg/aarch64_be
VPATH += $(AARCH64BE_SRC)

AARCH64BE_TEST_SRCS=$(notdir $(wildcard $(AARCH64BE_SRC)/*.c))
AARCH64BE_TESTS=$(AARCH64BE_TEST_SRCS:.c=)
#MULTIARCH_TESTS = $(MULTIARCH_SRCS:.c=)

# We need to specify big-endian cflags
CFLAGS +=-mbig-endian -ffreestanding
LDFLAGS +=-nostdlib

TESTS += $(AARCH64BE_TESTS)
