# -*- Mode: makefile -*-
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# MIPS64 - included from tests/tcg/Makefile.target
#

MIPS64_SRC=$(SRC_PATH)/tests/tcg/mips64
MIPS_OCTEON_SRC=$(SRC_PATH)/tests/tcg/mips/user/isa/octeon

# Set search path for all sources
VPATH 		+= $(MIPS64_SRC) $(MIPS_OCTEON_SRC)

MIPS64_TESTS=octeon-insns

TESTS += $(MIPS64_TESTS)

$(MIPS64_TESTS): CFLAGS+=-mabi=64

run-octeon-insns: QEMU_OPTS+=-cpu Octeon68XX
