obj-y += apic_common.o apic.o
obj-y += sga.o ioapic_common.o ioapic.o
obj-y += vmport.o
obj-y += debugexit.o
obj-y += kvm/
obj-y += pc-testdev.o

obj-y := $(addprefix ../,$(obj-y))

obj-y += multiboot.o smbios.o
obj-y += pc.o pc_piix.o pc_q35.o
obj-$(CONFIG_XEN) += xen_domainbuild.o xen_machine_pv.o

obj-y += kvmvapic.o
