/* List of comma-separated changed AML files to ignore */
"tests/data/acpi/x86/pc/DSDT",
"tests/data/acpi/x86/pc/DSDT.acpierst",
"tests/data/acpi/x86/pc/DSDT.acpihmat",
"tests/data/acpi/x86/pc/DSDT.bridge",
"tests/data/acpi/x86/pc/DSDT.cphp",
"tests/data/acpi/x86/pc/DSDT.dimmpxm",
"tests/data/acpi/x86/pc/DSDT.hpbridge",
"tests/data/acpi/x86/pc/DSDT.hpbrroot",
"tests/data/acpi/x86/pc/DSDT.ipmikcs",
"tests/data/acpi/x86/pc/DSDT.memhp",
"tests/data/acpi/x86/pc/DSDT.nohpet",
"tests/data/acpi/x86/pc/DSDT.numamem",
"tests/data/acpi/x86/pc/DSDT.roothp",
"tests/data/acpi/x86/q35/DSDT.cxl",
"tests/data/acpi/x86/q35/DSDT.viot",
