/* List of comma-separated changed AML files to ignore */
"tests/data/acpi/aarch64/virt/DSDT",
"tests/data/acpi/aarch64/virt/DSDT.acpihmatvirt",
"tests/data/acpi/aarch64/virt/DSDT.memhp",
"tests/data/acpi/aarch64/virt/DSDT.pxb",
"tests/data/acpi/aarch64/virt/DSDT.topology",
"tests/data/acpi/loongarch64/virt/DSDT.memhp",
"tests/data/acpi/loongarch64/virt/DSDT.topology",
"tests/data/acpi/loongarch64/virt/DSDT.numamem",
"tests/data/acpi/loongarch64/virt/DSDT",
"tests/data/acpi/x86/microvm/DSDT.pcie",
"tests/data/acpi/riscv64/virt/DSDT",
