#ifndef LINUX_USER_TARGET_MMAN_H
#define LINUX_USER_TARGET_MMAN_H

#ifndef TARGET_MADV_NORMAL
#define TARGET_MADV_NORMAL 0
#endif

#ifndef TARGET_MADV_RANDOM
#define TARGET_MADV_RANDOM 1
#endif

#ifndef TARGET_MADV_SEQUENTIAL
#define TARGET_MADV_SEQUENTIAL 2
#endif

#ifndef TARGET_MADV_WILLNEED
#define TARGET_MADV_WILLNEED 3
#endif

#ifndef TARGET_MADV_DONTNEED
#define TARGET_MADV_DONTNEED 4
#endif

#ifndef TARGET_MADV_FREE
#define TARGET_MADV_FREE 8
#endif

#ifndef TARGET_MADV_REMOVE
#define TARGET_MADV_REMOVE 9
#endif

#ifndef TARGET_MADV_DONTFORK
#define TARGET_MADV_DONTFORK 10
#endif

#ifndef TARGET_MADV_DOFORK
#define TARGET_MADV_DOFORK 11
#endif

#ifndef TARGET_MADV_MERGEABLE
#define TARGET_MADV_MERGEABLE 12
#endif

#ifndef TARGET_MADV_UNMERGEABLE
#define TARGET_MADV_UNMERGEABLE 13
#endif

#ifndef TARGET_MADV_HUGEPAGE
#define TARGET_MADV_HUGEPAGE 14
#endif

#ifndef TARGET_MADV_NOHUGEPAGE
#define TARGET_MADV_NOHUGEPAGE 15
#endif

#ifndef TARGET_MADV_DONTDUMP
#define TARGET_MADV_DONTDUMP 16
#endif

#ifndef TARGET_MADV_DODUMP
#define TARGET_MADV_DODUMP 17
#endif

#ifndef TARGET_MADV_WIPEONFORK
#define TARGET_MADV_WIPEONFORK 18
#endif

#ifndef TARGET_MADV_KEEPONFORK
#define TARGET_MADV_KEEPONFORK 19
#endif

#ifndef TARGET_MADV_COLD
#define TARGET_MADV_COLD 20
#endif

#ifndef TARGET_MADV_PAGEOUT
#define TARGET_MADV_PAGEOUT 21
#endif

#ifndef TARGET_MADV_POPULATE_READ
#define TARGET_MADV_POPULATE_READ 22
#endif

#ifndef TARGET_MADV_POPULATE_WRITE
#define TARGET_MADV_POPULATE_WRITE 23
#endif

#ifndef TARGET_MADV_DONTNEED_LOCKED
#define TARGET_MADV_DONTNEED_LOCKED 24
#endif


#ifndef TARGET_MS_ASYNC
#define TARGET_MS_ASYNC 1
#endif

#ifndef TARGET_MS_INVALIDATE
#define TARGET_MS_INVALIDATE 2
#endif

#ifndef TARGET_MS_SYNC
#define TARGET_MS_SYNC 4
#endif

#endif
