#ifndef M68K_TARGET_SYSCALL_H
#define M68K_TARGET_SYSCALL_H

#define UNAME_MACHINE "m68k"
#define UNAME_MINIMUM_RELEASE "2.6.32"

#define TARGET_MCL_CURRENT 1
#define TARGET_MCL_FUTURE  2
#define TARGET_MCL_ONFAULT 4
#define TARGET_WANT_OLD_SYS_SELECT

#endif /* M68K_TARGET_SYSCALL_H */
