#define SIZE_GRHWCONFIG 148
#define SIZE_GRVERTEX 60
#define SIZE_GRSTATE 312
#define SIZE_GRTEXINFO 20
#define SIZE_GRSSTPERFSTATS 20
#define SIZE_GRLFBINFO 20
#define SIZE_GU3DFHEADER 24
#define SIZE_GU3DFINFO 1056
#define SIZE_GUTEXTABLE 1024
#define SIZE_GUNCCTABLE 112
#define SIZE_GUTEXPALETTE 1024
#define SIZE_GRMIPMAPINFO 196
#define SIZE_GRRESOLUTION 16
#ifndef GLIDE2X_IMPL_H
static const char buildstr[] = __REV__ __TIME__" "__DATE__" build ";
#endif
