# -*- Mode: makefile -*-
#
# HPPA specific tweaks - specifically masking out broken tests

# On parisc Linux supports 4K/16K/64K (but currently only 4k works)
EXTRA_RUNS+=run-test-mmap-4096 # run-test-mmap-16384 run-test-mmap-65536

# This triggers failures for hppa-linux about 1% of the time
# HPPA is the odd target that can't use the sigtramp page;
# it requires the full vdso with dwarf2 unwind info.
run-signals: signals
	$(call skip-test, $<, "BROKEN awaiting vdso support")
run-plugin-signals-with-%:
	$(call skip-test, $<, "BROKEN awaiting vdso support")
