# -*- Mode: makefile -*-
#
# HPPA specific tweaks - specifically masking out broken tests

# On parisc Linux supports 4K/16K/64K (but currently only 4k works)
EXTRA_RUNS+=run-test-mmap-4096 # run-test-mmap-16384 run-test-mmap-65536

# There is a race that causes this to fail about 1% of the time
run-signals: signals
	$(call skip-test, $<, "BROKEN awaiting vdso support")
