# nios2 specific test tweaks

# Currently nios2 signal handling is broken
run-signals: signals
	$(call skip-test, $<, "BROKEN")
run-plugin-signals-with-%:
	$(call skip-test, $<, "BROKEN")
run-linux-test: linux-test
	$(call skip-test, $<, "BROKEN")
run-plugin-linux-test-with-%:
	$(call skip-test, $<, "BROKEN")
