softmmu-main-y = softmmu/main.o

obj-y += arch_init.o
obj-y += cpus.o
obj-y += cpu-throttle.o
obj-y += balloon.o
obj-y += ioport.o
obj-y += memory.o
obj-y += memory_mapping.o

obj-y += qtest.o

obj-y += vl.o
vl.o-cflags := $(GPROF_CFLAGS) $(SDL_CFLAGS)
