# -*- Mode: makefile -*-
#
# ppc64 specific tweaks

VPATH += $(SRC_PATH)/tests/tcg/ppc64
VPATH += $(SRC_PATH)/tests/tcg/ppc64le

ifneq ($(DOCKER_IMAGE)$(CROSS_CC_HAS_POWER8_VECTOR),)
PPC64_TESTS=bcdsub non_signalling_xscv
endif
$(PPC64_TESTS): CFLAGS += -mpower8-vector

PPC64_TESTS += byte_reverse
PPC64_TESTS += mtfsf
ifneq ($(DOCKER_IMAGE)$(CROSS_CC_HAS_POWER10),)
run-byte_reverse: QEMU_OPTS+=-cpu POWER10
run-plugin-byte_reverse-with-%: QEMU_OPTS+=-cpu POWER10
else
byte_reverse:
	$(call skip-test, "BUILD of $@", "missing compiler support")
run-byte_reverse:
	$(call skip-test, "RUN of byte_reverse", "not built")
run-plugin-byte_reverse-with-%:
	$(call skip-test, "RUN of byte_reverse ($*)", "not built")
endif

PPC64_TESTS += signal_save_restore_xer

TESTS += $(PPC64_TESTS)
