# -*- Mode: makefile -*-
#
# ppc64le specific tweaks

VPATH += $(SRC_PATH)/tests/tcg/ppc64le

ifneq ($(DOCKER_IMAGE)$(CROSS_CC_HAS_POWER8_VECTOR),)
PPC64LE_TESTS=bcdsub
endif
bcdsub: CFLAGS += -mpower8-vector

TESTS += $(PPC64LE_TESTS)
