# -*- Mode: makefile -*-
#
# MIPS - included from tests/tcg/Makefile.target
#

MIPS_SRC=$(SRC_PATH)/tests/tcg/mips

# Set search path for all sources
VPATH 		+= $(MIPS_SRC)

# hello-mips is 32 bit only
ifeq ($(findstring 64,$(TARGET_NAME)),)
MIPS_TESTS=hello-mips

TESTS += $(MIPS_TESTS)

hello-mips: CFLAGS+=-mno-abicalls -fno-PIC -mabi=32
hello-mips: LDFLAGS+=-nostdlib
endif
